server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

live:
  session:
    ttl-hours: 4   # Redis key TTL for an active session
